Use int instead of float for progress bar update
This fixes:

TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

Closes https://github.com/fmi-faim/napari-psf-analysis/issues/55.